### PR TITLE
Fix CSS directory

### PR DESCRIPTION
**Pull request by itsmingjie**

### CODE REVIEW

**Comment by itsmingjie** [comment]
me waiting

**Comment by itsmingjie** [comment]
still waiting

**Comment by itsmingjie** [comment]
owooooooooooooowuwwwwwwwwwwwwwwwwwwwwwuuuuuuuuuuuuuuuu

**Comment by megancui** [comment]
> owooooooooooooowuwwwwwwwwwwwwwwwwwwwwwuuuuuuuuuuuuuuuu

shut up

**Pull request merged**
